"""change opinion tittle to title

Revision ID: 7af87e7da338
Revises: bfc2b260cbe3
Create Date: 2026-03-14 12:41:20.065642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af87e7da338'
down_revision = 'bfc2b260cbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=False))
        batch_op.alter_column('tittle', new_column_name='title', existing_type=sa.String(length=128))
        #batch_op.drop_column('tittle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.alter_column('title', new_column_name='tittle', existing_type=sa.String(length=128))
        #batch_op.add_column(sa.Column('tittle', sa.VARCHAR(length=128), nullable=False))
        #batch_op.drop_column('title')

    # ### end Alembic commands ###
