"""added some updates to fields: OpinionStatus, UserRole, idexes to timestamp

Revision ID: d082183e2f57
Revises: 7af87e7da338
Create Date: 2026-03-15 14:43:55.558774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd082183e2f57'
down_revision = '7af87e7da338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='opinionstatus'),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'USER', name='userrole'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='opinionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_log_timestamp'))

    # ### end Alembic commands ###
